version: '2.2'
services:
  lab:
    build: .
    command: jupyter lab --port=8889 --ip='*' --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''
    ports:
     - "8889:8889"
  build:
    build: .
    command: npm run watch
    init: true
    volumes:
       - ".:/jupyterlab_nbprovenance"
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    command: cypress run
    init: true
    working_dir: /jupyterlab_nbprovenance
    volumes:
      - ".:/jupyterlab_nbprovenance"
    environment:
      CYPRESS_BASE_URL: "http://lab:8889"
