name: nbprov-demo
channels:
  - defaults
dependencies:
  - python
  - jupyterlab[version='=2.3.2']
  - nodejs[version='>=10']
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - vega_datasets
  - altair
  - scipy
  - scikit-learn
